exch2exch.Differences Class Reference
Public Member Functions
def __init__ (self, rates, mb, ok)
def __str__ (self)
def getABuySell (self)
def getALast (self)
def getCoinName (self)
def getMaxDelta (self)
def getMaxGain (self)
def getMinDelta (self)
def getMinGain (self)
def getRBuySell (self)
def getRLast (self)
Public Attributes
aBuySell
aLast
coinName
dmax
dmin
gmax
gmin
mb
ok
rates
rBuySell
rLast
Detailed Description
Definition at line 105 of file exch2exch.py.
Constructor & Destructor Documentation
__init__()
def exch2exch.Differences.__init__ (self, rates, mb, ok)
Definition at line 106 of file exch2exch.py.
    def __init__ (self, rates, mb, ok):
        self.rates = rates
        self.mb = mb
        self.ok = ok
        
        # TODO check the two coins
        self.coinName = mb.getCoinName ()
        
# self.dmin = mb.getLow () - ok.getLow ()
        self.dmax = mb.getHigh () - ok.getLow ()
        self.dmin = mb.getLow () - ok.getHigh ()
        
        self.gmin = 100.0 * self.dmin / ok.getHigh ()
        self.gmax = 100.0 * self.dmax / ok.getLow ()
        
        self.aBuySell = mb.getBuy () - ok.getSell ()
        self.rBuySell = 100.0 * self.aBuySell / ok.getBuy ()
        
        self.aLast = mb.getLast () - ok.getLast ()
        self.rLast = 100.0 * self.aLast / ok.getLast ()
        
Member Function Documentation
__str__()
def exch2exch.Differences.__str__ (self)
Definition at line 154 of file exch2exch.py.
References exch2exch.Differences.getABuySell(), exch2exch.Differences.getALast(), exch2exch.XbtPrices.getCoinName(), exch2exch.Differences.getCoinName(), exch2exch.Differences.getMaxDelta(), exch2exch.Differences.getMaxGain(), exch2exch.Differences.getMinDelta(), exch2exch.Differences.getMinGain(), exch2exch.Differences.getRBuySell(), exch2exch.Differences.getRLast(), exch2exch.Differences.mb, exch2exch.Differences.ok, and exch2exch.Differences.rates.
    def __str__ (self):
        result = ""
        
        oname = self.ok.getExchangeName ()
        mname = self.mb.getExchangeName ()
        sname = self.rates.getServiceName ()
        
        fmt = "Calculation between {0} and {1} rates, with conversion from {2}"
        result = fmt.format (oname, mname, sname)
        
        # TODO create evaluation for 24h and for the most recent sell/buy
        
        fmt = "\nExtrema:\n\tAbsolute: Minimum {0:.4f}, maximum {1:.4f}"
        result += fmt.format (self.getMinDelta (), self.getMaxDelta ())
        
        fmt = "\n\tRelative: minimum {0:.4f} %, maximum {1:.4f} %"
        result += fmt.format (self.getMinGain (), self.getMaxGain ())
        
        fmt = "\nBuy {0}, sell {1}:"
        result += fmt.format (oname, mname)
        fmt = "\n\tAbsolute: {0:.4f} {1}"
        result += fmt.format (self.getABuySell (), self.getCoinName ())
        fmt = "\n\tRelative: {0:.4f} %"
        result += fmt.format (self.getRBuySell ())
        
        fmt = "\nLast transactions at {0} and {1}:"
        result += fmt.format (oname, mname)
        fmt = "\n\tAbsolute: {0:.4f} {1}"
        result += fmt.format (self.getALast (), self.getCoinName ())
        fmt = "\n\tRelative: {0:.4f} %"
        result += fmt.format (self.getRLast ())
        
        # Normal function termination
        return result
#
#
# Google section
#
getABuySell()
def exch2exch.Differences.getABuySell (self)
Definition at line 139 of file exch2exch.py.
References exch2exch.Differences.aBuySell.
Referenced by exch2exch.Differences.__str__().
    def getABuySell (self):
        return self.aBuySell
        
getALast()
def exch2exch.Differences.getALast (self)
Definition at line 145 of file exch2exch.py.
References exch2exch.Differences.aLast.
Referenced by exch2exch.Differences.__str__().
    def getALast (self):
        return self.aLast
        
getCoinName()
def exch2exch.Differences.getCoinName (self)
Definition at line 151 of file exch2exch.py.
References exch2exch.Differences.coinName.
Referenced by exch2exch.Differences.__str__().
    def getCoinName (self):
        return self.coinName
        
getMaxDelta()
def exch2exch.Differences.getMaxDelta (self)
Definition at line 130 of file exch2exch.py.
References exch2exch.Differences.dmax.
Referenced by raw_urlparser.Differences.__str__(), and exch2exch.Differences.__str__().
    def getMaxDelta (self):
        return self.dmax
        
getMaxGain()
def exch2exch.Differences.getMaxGain (self)
Definition at line 136 of file exch2exch.py.
References exch2exch.Differences.gmax.
Referenced by exch2exch.Differences.__str__().
    def getMaxGain (self):
        return self.gmax
        
getMinDelta()
def exch2exch.Differences.getMinDelta (self)
Definition at line 127 of file exch2exch.py.
References exch2exch.Differences.dmin.
Referenced by raw_urlparser.Differences.__str__(), and exch2exch.Differences.__str__().
    def getMinDelta (self):
        return self.dmin
        
getMinGain()
def exch2exch.Differences.getMinGain (self)
Definition at line 133 of file exch2exch.py.
References exch2exch.Differences.gmin.
Referenced by exch2exch.Differences.__str__().
    def getMinGain (self):
        return self.gmin
        
getRBuySell()
def exch2exch.Differences.getRBuySell (self)
Definition at line 142 of file exch2exch.py.
References exch2exch.Differences.rBuySell.
Referenced by exch2exch.Differences.__str__().
    def getRBuySell (self):
        return self.rBuySell
        
getRLast()
def exch2exch.Differences.getRLast (self)
Definition at line 148 of file exch2exch.py.
References exch2exch.Differences.rLast.
Referenced by exch2exch.Differences.__str__().
    def getRLast (self):
        return self.rLast
        
Member Data Documentation
aBuySell
exch2exch.Differences.aBuySell
Definition at line 121 of file exch2exch.py.
Referenced by exchange.DiffTracker.__str__(), exchange.DiffTracker.calc(), exchange.DiffTracker.dumps(), and exch2exch.Differences.getABuySell().
aLast
exch2exch.Differences.aLast
Definition at line 124 of file exch2exch.py.
Referenced by exchange.DiffTracker.__str__(), exchange.DiffTracker.calc(), exchange.DiffTracker.dumps(), and exch2exch.Differences.getALast().
coinName
exch2exch.Differences.coinName
Definition at line 112 of file exch2exch.py.
Referenced by exch2exch.Differences.getCoinName().
dmax
exch2exch.Differences.dmax
Definition at line 115 of file exch2exch.py.
Referenced by raw_urlparser.Differences.getMaxDelta(), and exch2exch.Differences.getMaxDelta().
dmin
exch2exch.Differences.dmin
Definition at line 116 of file exch2exch.py.
Referenced by raw_urlparser.Differences.getMinDelta(), and exch2exch.Differences.getMinDelta().
gmax
exch2exch.Differences.gmax
Definition at line 119 of file exch2exch.py.
Referenced by exch2exch.Differences.getMaxGain().
gmin
exch2exch.Differences.gmin
Definition at line 118 of file exch2exch.py.
Referenced by exch2exch.Differences.getMinGain().
mb
exch2exch.Differences.mb
Definition at line 108 of file exch2exch.py.
Referenced by exch2exch.Differences.__str__().
ok
exch2exch.Differences.ok
Definition at line 109 of file exch2exch.py.
Referenced by raw_urlparser.Differences.__str__(), and exch2exch.Differences.__str__().
rates
exch2exch.Differences.rates
Definition at line 107 of file exch2exch.py.
Referenced by raw_urlparser.Differences.__str__(), exch2exch.Differences.__str__(), exchange.DiffTracker.__str__(), exchange.DiffTracker.calc(), and exchange.DiffTracker.dumps().
rBuySell
exch2exch.Differences.rBuySell
Definition at line 122 of file exch2exch.py.
Referenced by exchange.DiffTracker.__str__(), exchange.DiffTracker.calc(), exchange.DiffTracker.dumps(), and exch2exch.Differences.getRBuySell().
rLast
exch2exch.Differences.rLast
Definition at line 125 of file exch2exch.py.
Referenced by exchange.DiffTracker.__str__(), exchange.DiffTracker.calc(), exchange.DiffTracker.dumps(), and exch2exch.Differences.getRLast().
The documentation for this class was generated from the following file:
/home/hilton/github/exch2exh/exch2exch.py