exchange.Exchange Class Reference
Public Member Functions
def __init__ (self)
def __repr__ (self)
def __str__ (self)
def dnload_orderbook (self)
def dnload_ticker (self)
def dnload_trades (self)
def get_exch_name (self)
def get_orderbook (self)
def get_original (self)
def get_ticker (self)
def get_trades (self)
def mk_ticker (self)
def process_orderbook (self)
def process_ticker (self)
def process_trades (self)
Public Attributes
original
ticker
trades
Static Public Attributes
string U_ORDRBK = ''
string U_TICKER = ''
string U_TRADES = ''
Detailed Description
Definition at line 127 of file exchange.py.
Constructor & Destructor Documentation
def exchange.Exchange.__init__ (self)
Definition at line 134 of file exchange.py.
00134 def __init__ (self):
# self.dnload_ticker ()
# self.process_ticker ()
        pass
    
Member Function Documentation
def exchange.Exchange.__repr__ (self)
Definition at line 212 of file exchange.py.
00212 def __repr__ (self):
        result = "{0} ()".format (type (self).__name__)
        
        # Normal function termination
        return result
        
def exchange.Exchange.__str__ (self)
Definition at line 208 of file exchange.py.
00208 def __str__ (self):
        # TODO raise exception
        pass
        
def exchange.Exchange.dnload_orderbook (self)
Definition at line 182 of file exchange.py.
References exchange.Exchange.trades.
00182 def dnload_orderbook (self):
        url = self.__class__.U_ORDRBK
        f = urllib.request.urlopen (url)
        
        line = f.readline ()
# print (line)
        
        self.trades = json.loads (line.decode (encoding='utf-8'))
# print (self.ticker)
        
def exchange.Exchange.dnload_ticker (self)
Definition at line 139 of file exchange.py.
00139 def dnload_ticker (self):
        url = self.__class__.U_TICKER
# print (url)
        f = urllib.request.urlopen (url)
        
        line = f.readline ()
# print (line)
00146 self.original = line.decode (encoding = 'utf-8')
        
00148 self.ticker = json.loads (line.decode (encoding='utf-8'))
# print (self.ticker)
        
def exchange.Exchange.dnload_trades (self)
Definition at line 163 of file exchange.py.
00163 def dnload_trades (self):
        url = self.__class__.U_TRADES
# print (url)
        f = urllib.request.urlopen (url)
        
        line = f.readline ()
# print (line)
        
00171 self.trades = json.loads (line.decode (encoding='utf-8'))
# print (self.ticker)
        
def exchange.Exchange.get_exch_name (self)
Definition at line 200 of file exchange.py.
00200 def get_exch_name (self):
        # TODO raise exception
        pass
    
def exchange.Exchange.get_orderbook (self)
Definition at line 196 of file exchange.py.
00196 def get_orderbook (self):
        self.dnload_orderbook ()
        self.process_orderbook ()
    
def exchange.Exchange.get_original (self)
Definition at line 204 of file exchange.py.
00204 def get_original (self):
        # TODO raise exception
        pass
        
def exchange.Exchange.get_ticker (self)
Definition at line 155 of file exchange.py.
00155 def get_ticker (self):
        self.dnload_ticker ()
        self.process_ticker ()
    
def exchange.Exchange.get_trades (self)
Definition at line 178 of file exchange.py.
00178 def get_trades (self):
        self.dnload_trades ()
        self.process_trades ()
    
def exchange.Exchange.mk_ticker (self)
Definition at line 159 of file exchange.py.
00159 def mk_ticker (self):
        # TODO raise exception
        pass
    
def exchange.Exchange.process_orderbook (self)
Definition at line 192 of file exchange.py.
Referenced by exchange.Exchange.get_orderbook().
00192 def process_orderbook (self):
        # TODO raise exception
        pass
    
def exchange.Exchange.process_ticker (self)
Definition at line 151 of file exchange.py.
Referenced by exchange.Exchange.get_ticker().
00151 def process_ticker (self):
        # TODO raise exception
        pass
    
def exchange.Exchange.process_trades (self)
Definition at line 174 of file exchange.py.
Referenced by exchange.Exchange.get_trades().
00174 def process_trades (self):
        # TODO raise exception
        pass
    
Member Data Documentation
exchange.Exchange.original
Definition at line 146 of file exchange.py.
Referenced by exchange.FoxBit.get_original(), exchange.MercadoBitcoin.get_original(), and exchange.OkCoin.get_original().
exchange.Exchange.ticker
Definition at line 148 of file exchange.py.
Referenced by exchange.FoxBit.mk_ticker(), and exchange.FoxBit.process_ticker().
exchange.Exchange.trades
Definition at line 171 of file exchange.py.
Referenced by exchange.Exchange.dnload_orderbook().
string exchange.Exchange.U_ORDRBK = '' [static]
Definition at line 130 of file exchange.py.
string exchange.Exchange.U_TICKER = '' [static]
Definition at line 128 of file exchange.py.
string exchange.Exchange.U_TRADES = '' [static]
Definition at line 129 of file exchange.py.
The documentation for this class was generated from the following file:
/home/hilton/github/exch2exh/exchange.py