e2e.Application Class Reference
Public Member Functions
def __init__ (self)
def genExpectations (self)
def genOutput (self)
def getParameters (self)
def interpretArgs (self)
def outAllRates (self)
def outDestinationExchange (self)
def outMainRates (self)
def outOriginExchange (self)
def parseCmdLine (self)
Public Attributes
args
params
prefix
suffix
Detailed Description
Definition at line 133 of file e2e.py.
Constructor & Destructor Documentation
__init__()
def e2e.Application.__init__ (self)
Definition at line 134 of file e2e.py.
    def __init__ (self):
        d = start_time.getDatetime ()
        self.suffix = d.strftime ('%Y%m%d_%H%M')
        self.prefix = 'e2e'
        self.params = None
    
Member Function Documentation
genExpectations()
def e2e.Application.genExpectations (self)
Definition at line 487 of file e2e.py.
References e2e.Application.getParameters().
    def genExpectations (self):
        params = self.getParameters ()
        # Create the difference
        origin = params.getOrigin ()
        orgTicker = origin.mkTicker ()
        destination = params.getDestination ()
        dstTicker = destination.mkTicker ()
        mainRates = params.getMainRates ()
        
        diff = exchange.DiffTracker (mainRates, dstTicker, orgTicker)
       
        # Generate the difference
        diff.calc ()
        
        # TODO output the formatted difference report
        outFile = params.getRepConclusionOutput ()
        line = str (diff) + "\n"
        outFile.write (line)
        
        outFile.close ()
        
        # TODO output the JSON differene report
        outFile = params.getJsonConclusionOutput ()
        line = diff.dumps () + "\n"
        outFile.write (line)
        
        outFile.close ()
            
genOutput()
def e2e.Application.genOutput (self)
Definition at line 516 of file e2e.py.
    def genOutput (self):
        pass
getParameters()
def e2e.Application.getParameters (self)
Definition at line 386 of file e2e.py.
References e2e.Application.params.
Referenced by e2e.Application.genExpectations(), e2e.Application.outAllRates(), e2e.Application.outDestinationExchange(), e2e.Application.outMainRates(), and e2e.Application.outOriginExchange().
    def getParameters (self):
        return self.params
            
interpretArgs()
def e2e.Application.interpretArgs (self)
Definition at line 183 of file e2e.py.
References e2e.Application.args, e2e.Application.params, e2e.Application.prefix, and e2e.Application.suffix.
    def interpretArgs (self):
        result = Parameters ()
        
# # Open summary file
# if self.args.summary == None:
# try:
# sum_nam = self.prefix + '_' + self.suffix + '.sum'
# sum_f = open (sum_nam, 'w')
#
# except IOError:
# # TODO an application specific msg here
# raise
# else:
# sum_f = sys.__stdout__
#
# result.setSummaryOutput (sum_f)
#
# # TODO Open output files for destination exchange
# try:
# cnc_nam = self.prefix + '_conclusion'
# cnc_nam += '_' + self.suffix + '.json'
# cnc_f = open (cnc_nam, 'w')
#
# except IOError:
# # TODO an application specific msg here
# raise
#
# result.setConclusionOutput (cnc_f)
            
        # TODO confirm that destinatian and origin exchanges are not equal
        args = self.args
        if args.origin == args.destination:
            fmt = 'ERROR: Origin exchange {0} equal to destination {1}'
            msg = fmt.format (args.origin, args.destination)
            raise Exception (msg)
        # TODO get exchange names
        gfExchange = gen_factory.GenFactory (
      exchange.Exchange)
        exchNames = gfExchange.validClassNames ()
        
        # TODO validate destination exchange
        if not gfExchange.isValidClassName (args.destination):
            fmt = 'ERROR: Destination exchange {0} is not a valid '
            fmt += 'exchange name.\n'
            fmt += '\tShould be one of {1}'
            msg = fmt.format (args.destination, exchNames)
            raise Exception (msg)
            
        # TODO validate origin exchange
        if not gfExchange.isValidClassName (args.origin):
            fmt = 'ERROR: Origin exchange {0} is not a valid exchange name.\n'
            fmt += '\tShould be one of {1}'
            msg = fmt.format (args.origin, exchNames)
            raise Exception (msg)
        
        # TODO open connection with destination exchange
        dstExchange = gfExchange.genObject (args.destination)
        result.setDestination (dstExchange)
            
        # TODO Open output files for destination exchange
        try:
            dst_nam = self.prefix + '_' + dstExchange.get_exch_prefix ()
            dst_nam += '_' + self.suffix + '.json'
            e2e_dst_f = open (dst_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
            
        result.setDestinationOutput (e2e_dst_f)
            
        try:
            dst_nam = dstExchange.get_exch_prefix ()
            dst_nam += '_' + self.suffix + '.json'
            dst_f = open (dst_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
            
        result.setRawDestinationOutput (dst_f)
            
        # TODO open connection with origin exchange
        orgExchange = gfExchange.genObject (args.origin)
        result.setOrigin (orgExchange)
            
        # TODO Open output files for origin exchange
        try:
            org_nam = self.prefix + '_' + orgExchange.get_exch_prefix ()
            org_nam += '_' + self.suffix + '.json'
            e2e_org_f = open (org_nam, 'w')
            
        except IOError:
            # TODO an application specific2 msg here
            raise
        result.setOriginOutput (e2e_org_f)
            
        try:
            org_nam = orgExchange.get_exch_prefix ()
            org_nam += '_' + self.suffix + '.json'
            org_f = open (org_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
            
        result.setRawOriginOutput (org_f)
            
        # TODO open connection with main rate service
        gfRates = gen_factory.GenFactory (rates.Rates)
        rates_names = gfRates.validClassNames ()
        # TODO validate main rate service
        if not gfRates.isValidClassName (args.mainRates):
            fmt = 'ERROR: Main rates service {0} '
            fmt += 'is not a valid rates name.\n'
            fmt += '\tShould be one of {1}'
            msg = fmt.format (args.mainRates, rates_names)
            raise Exception (msg)
        mainRates = gfRates.genObject (args.mainRates)
        result.setMainRates (mainRates)
        
        # TODO Open output file for main rate service
        try:
            rat_nam = mainRates.getServicePrefix () + '_'
            rat_nam += self.suffix + '.rat'
            rat_f = open (rat_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
        result.setMainRatesOutput (rat_f)
            
        # TODO open connections with auxiliary rate services
        allRatesNames = []
        for rateName in rates_names:
# if rateName == args.mainRates:
# continue
            
            allRatesNames.append (rateName)
        result.allRates = []
        for rateName in allRatesNames:
            result.allRates.append (gfRates.genObject (rateName))
            
        try:
            allrat_nam = 'all_rates' + '_'
            allrat_nam += self.suffix + '.rat'
            allrat_f = open (allrat_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
        result.setAllRatesOutput (allrat_f)
            
        try:
            conc_nam = 'conc_' + orgExchange.get_exch_prefix ()
            conc_nam += '_' + dstExchange.get_exch_prefix () + '_'
            conc_nam += self.suffix + '.rep'
            conc_f = open (conc_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
        result.setRepConclusionOutput (conc_f)
            
        try:
            conc_nam = 'conc_' + orgExchange.get_exch_prefix ()
            conc_nam += '_' + dstExchange.get_exch_prefix () + '_'
            conc_nam += self.suffix + '.json'
            conc_f = open (conc_nam, 'w')
            
        except IOError:
            # TODO an application specific msg here
            raise
        result.setJsonConclusionOutput (conc_f)
        
        self.params = result
        
        args = self.args
        if args.verbose:
            repFile = result.getRepConclusionOutput ()
                        
            
            lines = ['', '', '', '', '']
            lines[0] = 'Verbose output enabled\n'
            lines[1] = 'Main rate service: {0}'.format (args.mainRates)
            lines[2] = 'Exchanges'
            lines[3] = 'Origin: {0}'.format (args.origin)
            lines[4] = 'Destination: {0}\n'.format (args.destination)
            for line in lines:
                repFile.write (line + '\n')
            
        # Normal function termination
        return result
        
outAllRates()
def e2e.Application.outAllRates (self)
Definition at line 398 of file e2e.py.
References e2e.Application.getParameters().
    def outAllRates (self):
        # TODO calculate average rate and individual differences
        params = self.getParameters ()
        allRates = params.getAllRates ()
        outFile = params.getAllRatesOutput ()
        repFile = params.getRepConclusionOutput ()
        
        repFile.write ("\nExchange services\n")
        
        for theseRates in allRates:
            line = str (theseRates) + "\n"
            outFile.write (line)
            repFile.write (line)
        repFile.write ('\n')
        
        outFile.close ()
        repFile.flush ()
    
outDestinationExchange()
def e2e.Application.outDestinationExchange (self)
Definition at line 452 of file e2e.py.
References e2e.Application.getParameters().
    def outDestinationExchange (self):
        params = self.getParameters ()
        
        # Get origin exchange data
        destination = params.getDestination ()
        destination.get_ticker ()
        ticker = destination.mkTicker ()
        # Output raw exchange data
        outFile = params.getRawDestinationOutput ()
        line = str (destination.getOriginalTicker ()) + "\n"
        outFile.write (line)
        
        outFile.close ()
    
        # Output e2e exchange data
        outFile = params.getDestinationOutput ()
        line = str (ticker.dumps ()) + "\n"
        outFile.write (line)
        
        outFile.close ()
        
        # TODO output origin data as report
        repFile = params.getRepConclusionOutput ()
        line = "\nDestination exchange"
        repFile.write (line + '\n')
        
        line = str (ticker) + "\n"
        repFile.write (line)
        
        repFile.flush ()
    
        # Normal function termination
        return
    
outMainRates()
def e2e.Application.outMainRates (self)
Definition at line 389 of file e2e.py.
References e2e.Application.getParameters().
    def outMainRates (self):
        params = self.getParameters ()
        mainRates = params.getMainRates ()
        outFile = params.getMainRatesOutput ()
        line = str (mainRates) + "\n"
        outFile.write (line)
        
        outFile.close ()
    
outOriginExchange()
def e2e.Application.outOriginExchange (self)
Definition at line 417 of file e2e.py.
References e2e.Application.getParameters().
    def outOriginExchange (self):
        params = self.getParameters ()
        
        # Get origin exchange data
        origin = params.getOrigin ()
        origin.get_ticker ()
        ticker = origin.mkTicker ()
        # Output raw origin exchange data
        outFile = params.getRawOriginOutput ()
        line = str (origin.getOriginalTicker ()) + "\n"
        outFile.write (line)
        
        outFile.close ()
    
        # Output e2e origin exchange data
        outFile = params.getOriginOutput ()
        line = str (ticker.dumps ()) + "\n"
        outFile.write (line)
        
        outFile.close ()
        
        # TODO output origin data as report
        repFile = params.getRepConclusionOutput ()
        line = "\nOrigin exchange"
        repFile.write (line + '\n')
        
        line = str (ticker) + "\n"
        repFile.write (line)
        
        repFile.flush ()
    
        # Normal function termination
        return
    
parseCmdLine()
def e2e.Application.parseCmdLine (self)
Definition at line 140 of file e2e.py.
    def parseCmdLine (self):
        desc = 'Compare two exchanges for a round operation'
        parser = argparse.ArgumentParser (description = desc)
        
# desc = 'Summary report (Default is stdout)'
# parser.add_argument ('-s', '--summary', required = False,
# help = desc)
# desc = 'File name for the conclusion of the arbitrage'
# parser.add_argument ('-c', '--conclusion', required = True,
# help = desc)
        parser.add_argument ('-m', '--main', metavar = "RATES",
                             default = 'Google',
                             help = 'Main rate service')
# parser.add_argument ('-a', '--alternative', metavar = "RATES",
# default = 'XRates',
# help = 'Alternative rate service')
        parser.add_argument ('-o', '--origin', metavar = "EXCHANGE",
                             required = True,
                             help = 'Origin exchange')
        parser.add_argument ('-d', '--destination', metavar = "EXCHANGE",
                             required = True,
                             help = 'Destination exchange')
        parser.add_argument ('-v', '--verbose', action = "store_true",
                             help = 'Increase output verbosity')
                             
        args = parser.parse_args ()
        
        # TODO complete the copy of cmdline parameters
        
        result = Args ()
# result.summary = args.summary
# result.conclusion = args.conclusion
        result.mainRates = args.main
# result.altRates = args.alternative
        result.origin = args.origin
        result.destination = args.destination
        result.verbose = args.verbose
        
        self.args = result
        
        # Normal function termination
        return result
        
Member Data Documentation
args
e2e.Application.args
Definition at line 178 of file e2e.py.
Referenced by e2e.Application.interpretArgs().
params
e2e.Application.params
Definition at line 138 of file e2e.py.
Referenced by e2e.Application.getParameters(), and e2e.Application.interpretArgs().
prefix
e2e.Application.prefix
Definition at line 137 of file e2e.py.
Referenced by e2e.Application.interpretArgs().
suffix
e2e.Application.suffix
Definition at line 136 of file e2e.py.
Referenced by e2e.Application.interpretArgs().
The documentation for this class was generated from the following file:
/home/hilton/github/exch2exh/e2e.py